### ISSUE TITLE
Research RWX storage providers to be used with Baffles workloads

### ISSUE THREAD

**Issue by TheFutonEng** [defenseunicorns/baffles-matlab-demo#11]
As a Baffles user, I want shared storage local to the K8s cluster Baffles is running in, So that it's easier to share data with my colleagues.

# Acceptance Criteria

Given that Kubevirt VMs don't share data by default
When I launch VMs in Baffles I want the possibility of shared storage
Then end user collaboration is possible.

**Comment by TheFutonEng** [comment]
[Rook](https://rook.io/) appears to have the ability to provide RWX PVCs.  Tossed some messaged into various slack channels, pending some feedback before dedicating any time.

**Comment by TheFutonEng** [comment]
After some great feedback, going to try OpenEBS first as it appears to be what will be the quickest to get going (RWX article [here](https://openebs.io/docs/concepts/rwm)).

**Comment by TheFutonEng** [comment]
Deploying GCP cluster to do some testing.  Cluster will have Kubevirt and CDI.  Will mess around with an Ubuntu server VM to be able to quickly prototype.  Here's what we're trying to learn:

- How hard is it to install OpenEBS?
- How hard is it to use OpenEBS to expose a RWX PVC to Kubevirt VMs as a drive?

Some links that may be helpful in this regard:
 
- [OpenEBS for RWX](https://openebs.io/docs/concepts/rwm)
- [Persistent Storage in Kubevirt with Rook](https://kubevirt.io/2019/KubeVirt_storage_rook_ceph.html) (some Kubevirt things may be helpful

**Comment by TheFutonEng** [comment]
Helm repo details for OpenEBS can be found [here](https://github.com/openebs/charts/tree/main/charts/openebs).

**Comment by TheFutonEng** [comment]
The [quick start guide](https://openebs.io/docs/user-guides/quickstart#1-kubernetes-cluster-design) details that the the [ISCSI initiator](https://openebs.io/docs/user-guides/prerequisites#ubuntu) is required in order for OpenEBS to run.

**Comment by TheFutonEng** [comment]
Attempting to install the NFS provisioner via OpenEBS:

```
[rmengert@oakridge:~/projects/cdi]
$ helm install openebs openebs/openebs --namespace openebs \
> --set nfs-provisioner.enabled=true \
> --set legacy.enabled=false
NAME: openebs
LAST DEPLOYED: Mon Aug 15 14:19:15 2022
NAMESPACE: openebs
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Successfully installed OpenEBS.

Check the status by running: kubectl get pods -n openebs

The default values will install NDM and enable OpenEBS hostpath and device
storage engines along with their default StorageClasses. Use `kubectl get sc`
to see the list of installed OpenEBS StorageClasses.

**Note**: If you are upgrading from the older helm chart that was using cStor
and Jiva (non-csi) volumes, you will have to run the following command to include
the older provisioners:

helm upgrade openebs openebs/openebs \
	--namespace openebs \
	--set legacy.enabled=true \
	--reuse-values

For other engines, you will need to perform a few more additional steps to
enable the engine, configure the engines (e.g. creating pools) and create 
StorageClasses. 

For example, cStor can be enabled using commands like:

helm upgrade openebs openebs/openebs \
	--namespace openebs \
	--set cstor.enabled=true \
	--reuse-values

For more information, 
- view the online documentation at https://openebs.io/docs or
- connect with an active community on Kubernetes slack #openebs channel.
[rmengert@oakridge:~/projects/cdi]
$ 
```

**Comment by TheFutonEng** [comment]
Was able to create a PVC attached to the storage class:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openebs-nfs
  namespace: default
spec:
  storageClassName: openebs-kernel-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "10G"
```

```
[rmengert@Robs-MBP:~/projects/baffles-infra/demo-stuff]
$ kubectl apply -f nfs-pv-pvc.yaml 
persistentvolumeclaim/openebs-nfs created
[rmengert@Robs-MBP:~/projects/baffles-infra/demo-stuff]
$ 
```

Going to try and mount it into a VM next.

**Comment by TheFutonEng** [comment]
Ran into issues with the PVC, the VM never hit a ready state.  Destroying the cluster and redeploying everything as the removal of OpenEBS did not appear to be clean.

Following [this guide](https://github.com/openebs/dynamic-nfs-provisioner/blob/develop/docs/intro.md#quickstart) next.

**Comment by TheFutonEng** [comment]
Installing the NFS provisioner via the operator next.

```
$ kubectl apply -f https://openebs.github.io/charts/nfs-operator.yaml
```

**Comment by TheFutonEng** [comment]
The NFS PVC failed to provision when installing the operator.  The following error was in the events:

```
Events:
  Type     Reason              Age               From                         Message
  ----     ------              ----              ----                         -------
  Warning  ProvisioningFailed  7s (x2 over 21s)  persistentvolume-controller  storageclass.storage.k8s.io "openebs-hostpath" not found
```

The storageclass for openebs-hostpath is indeed NOT installed via the operator:

```
[rmengert@oakridge:~/projects/cdi]
$ kubectl get sc
NAME                   PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
local-path (default)   rancher.io/local-path   Delete          WaitForFirstConsumer   false                  17m
openebs-rwx            openebs.io/nfsrwx       Delete          Immediate              false                  10m
[rmengert@oakridge:~/projects/cdi]
$ 
```

Removing the operator and installing OpenEBS via Helm, but still following the [same guide](https://github.com/openebs/dynamic-nfs-provisioner/blob/develop/docs/intro.md#quickstart).

**Comment by TheFutonEng** [comment]
Current state:

- Deployed 3 node GCP cluster
- Deployed Kubevirt and CDI repo1 helm charts
- Deployed OpenEBS [helm chart](https://github.com/openebs/dynamic-nfs-provisioner/blob/develop/docs/intro.md#install-nfs-provisioner-through-helm)
- Deployed RWX storage class called OpenEBS and PVC (manifests [here](https://github.com/openebs/dynamic-nfs-provisioner/blob/develop/docs/intro.md#provision-nfs-volume))
- Deployed VM referencing the PVC as an additional disk:

VM Manifest
```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: nfs-test
  name: nfs-test
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: nfs-test
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: datavolumedisk1
          - disk:
              bus: virtio
            name: datavolumedisk2
          - disk:
              bus: virtio
            name: cloudinitdisk
        machine:
          type: ""
        resources:
          requests:
            memory: 1Gi
      terminationGracePeriodSeconds: 0
      volumes:
      - dataVolume:
          name: operating-system
        name: datavolumedisk1
      - dataVolume:
          name: nfs-share
        name: datavolumedisk2
      - cloudInitNoCloud:
          userData: |
            # add any custom logic you want to occur on startup here.
            echo “cloud-init script execution"
        name: cloudinitdisk
  dataVolumeTemplates:
  - metadata:
      name: operating-system
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 40Gi
      source:
        pvc:
          namespace: vm-images
          name: ubuntu-server-base
  - metadata:
      name: nfs-share
    spec:
      pvc:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 10Gi
      source:
        pvc:
          namespace: default
          name: openebs-nfs
```

Observed Behavior:

A PVC called nfs-share is created and forever stays in a 'Pending' state.

Pick up investigation from here.
